#getting base image from 
FROM nginx

MAINTAINER hady ibrahim <hadyib007@gmail.com>

RUN rm -rf /usr/share/nginx/html/*

#RUN rm -rf /etc/nginx/conf.d/*

#ADD ./default.conf /etc/nginx/conf.d

VOLUME /etc/nginx/conf.d/